export interface hotels{
    id: number,
    thumbnail: string,
    photos: string[],
    name: string,
    address: string,
    city: string,
    state: string,
    price: number | string,
    rating: number | string,
    reviews?: string[],
    originalPrice: number | string,
    slug: string
}

export interface initialState  {
    hotels: hotels[],
    totalNoHotels: number
}

export const hotelsData: hotels[] = [
    {
        id: 1,
        thumbnail: "/assets/hotel_tnagar1.avif",
        photos: ["/assets/hotel_tnagar1.avif", "/assets/hotel_demo4.avif", "/assets/hotel_demo2.avif", "/assets/hotel_demo3.avif"],
        name: "Spot On Jayam Residency",
        address: "near arumbakkam metro station",
        city: 'chennai',
        state: "tamil nadu",
        price: 1700,
        originalPrice: 3000,
        rating: 4.9,
        slug: "spot-on-jayam-residency",
    },
    {
        id: 2,
        thumbnail: "/assets/hotel_tnagar1.avif",
        photos: ["/assets/hotel_demo4.avif", "/assets/hotel_demo2.avif", "/assets/hotel_demo3.avif"],
        name: "Spot On Jayam Residency",
        address: "near arumbakkam metro station",
        city: 'chennai',
        state: "tamil nadu",
        price: 1700,
        originalPrice: 2500,
        rating: 4.9,
        slug: "spot-on-jayam-residency",
    },
    {
        id: 3,
        thumbnail: "/assets/hotel_tnagar1.avif",
        photos: ["/assets/hotel_demo4.avif", "/assets/hotel_demo2.avif", "/assets/hotel_demo3.avif"],
        name: "Spot On Jayam Residency",
        address: "near arumbakkam metro station",
        city: 'chennai',
        state: "tamil nadu",
        price: 1700,
        originalPrice: 2500,
        rating: 4.9,
        slug: "spot-on-jayam-residency",
    },
    {
        id: 4,
        thumbnail: "/assets/hotel_tnagar1.avif",
        photos: ["/assets/hotel_demo4.avif", "/assets/hotel_demo2.avif", "/assets/hotel_demo3.avif"],
        name: "Spot On Jayam Residency",
        address: "near arumbakkam metro station",
        city: 'chennai',
        state: "tamil nadu",
        price: 1700,
        originalPrice: 2500,
        rating: 4.9,
        slug: "spot-on-jayam-residency",
    },
    {
        id: 5,
        thumbnail: "/assets/hotel_tnagar1.avif",
        photos: ["/assets/hotel_demo4.avif", "/assets/hotel_demo2.avif", "/assets/hotel_demo3.avif"],
        name: "Spot On Jayam Residency",
        address: "near arumbakkam metro station",
        city: 'chennai',
        state: "tamil nadu",
        price: 1700,
        originalPrice: 2500,
        rating: 4.9,
        slug: "spot-on-jayam-residency",
    },
]